import fs from "fs/promises";
import path from "path";
import type { Newsletter } from "../schemas/newsletter.js";
import type { ArticleSummary } from "../schemas/newsletter.js";

const OUTPUT_DIR = path.resolve(process.cwd(), "output");

// ─── HTML Generator ───────────────────────────────────────────────────────────

export function generateHTML(
  content: { subject: string; title: string; introduction: string; conclusion: string },
  articles: ArticleSummary[]
): string {
  const articlesHtml = articles
    .map(
      (a, i) => `
  <div class="article">
    <h2>${i + 1}. ${escapeHtml(a.title)}</h2>
    <p class="source">Source: <a href="${escapeHtml(a.url)}" target="_blank" rel="noopener">${escapeHtml(a.source)}</a></p>
    <p>${escapeHtml(a.summary)}</p>
    <div class="why-matters">
      <strong>Why it matters:</strong> ${escapeHtml(a.whyItMatters)}
    </div>
    <p><a href="${escapeHtml(a.url)}" target="_blank" rel="noopener">Read full article →</a></p>
  </div>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(content.subject)}</title>
  <style>
    body {
      font-family: Georgia, 'Times New Roman', serif;
      max-width: 640px;
      margin: 0 auto;
      padding: 24px 16px;
      color: #1a1a1a;
      background: #ffffff;
      line-height: 1.7;
    }
    h1 { font-size: 28px; color: #0f172a; margin-bottom: 8px; }
    .tagline { color: #64748b; font-style: italic; margin-bottom: 32px; }
    .intro { font-size: 16px; border-left: 4px solid #6366f1; padding-left: 16px; color: #334155; }
    hr { border: none; border-top: 1px solid #e2e8f0; margin: 32px 0; }
    .article { margin-bottom: 40px; }
    .article h2 { font-size: 20px; color: #0f172a; margin-bottom: 6px; }
    .source { color: #64748b; font-size: 13px; margin-bottom: 12px; }
    .source a { color: #6366f1; text-decoration: none; }
    .why-matters {
      background: #f0f4ff;
      border-left: 4px solid #6366f1;
      padding: 12px 16px;
      margin: 12px 0;
      border-radius: 0 6px 6px 0;
      font-size: 14px;
      color: #374151;
    }
    .article a { color: #6366f1; font-size: 14px; }
    .conclusion { background: #f8fafc; padding: 20px; border-radius: 8px; font-size: 15px; color: #374151; }
    .footer { margin-top: 48px; text-align: center; font-size: 12px; color: #94a3b8; }
  </style>
</head>
<body>
  <h1>${escapeHtml(content.title)}</h1>
  <p class="tagline">Your weekly briefing on AI agent developments</p>

  <div class="intro">
    <p>${escapeHtml(content.introduction)}</p>
  </div>

  <hr />

  ${articlesHtml}

  <hr />

  <div class="conclusion">
    <p>${escapeHtml(content.conclusion)}</p>
  </div>

  <div class="footer">
    <p>Generated by Newsletter Agent &bull; ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
  </div>
</body>
</html>`;
}

// ─── Markdown Generator ──────────────────────────────────────────────────────

export function generateMarkdown(
  content: { subject: string; title: string; introduction: string; conclusion: string },
  articles: ArticleSummary[]
): string {
  const articlesmd = articles
    .map(
      (a, i) => `## ${i + 1}. ${a.title}

**Source:** [${a.source}](${a.url})

${a.summary}

> **Why it matters:** ${a.whyItMatters}

[Read more →](${a.url})`
    )
    .join("\n\n---\n\n");

  return `# ${content.title}

> Your weekly briefing on AI agent developments

${content.introduction}

---

${articlesmd}

---

## Closing Thoughts

${content.conclusion}

---

*Generated by Newsletter Agent · ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}*
`;
}

// ─── File Writer ──────────────────────────────────────────────────────────────

export async function saveNewsletterFiles(newsletter: Newsletter): Promise<string[]> {
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  const htmlPath = path.join(OUTPUT_DIR, "newsletter.html");
  const mdPath = path.join(OUTPUT_DIR, "newsletter.md");
  const emailPath = path.join(OUTPUT_DIR, "email.txt");

  await fs.writeFile(htmlPath, newsletter.html, "utf-8");
  await fs.writeFile(mdPath, newsletter.markdown, "utf-8");
  await fs.writeFile(
    emailPath,
    buildEmailFile(newsletter.subject, newsletter.markdown),
    "utf-8"
  );

  return ["newsletter.html", "newsletter.md", "email.txt"];
}

function buildEmailFile(subject: string, content: string): string {
  const separator = "-".repeat(40);
  return `To: subscribers@example.com
Subject: ${subject}

${separator}

${content}

${separator}

Generated by Newsletter Agent
${new Date().toISOString()}
`;
}

// ─── Utility ──────────────────────────────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
